import { createTheme } from '@mui/system';
import shadows from './shadows';

export const easing = {
  easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easeOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
  easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
  sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
};

const theme = createTheme({
  direction: 'ltr',
  breakpoints: {
    keys: ['xs', 'sm', 'md', 'lg', 'xl'],
    values: {
      xs: 0,
      sm: 600,
      md: 900,
      lg: 1200,
      xl: 1536,
    },
    up: () => {},
    down: () => {},
    only: () => {},
    not: () => {},
    unit: 'px',
  },
  components: {},
  palette: {
    mode: 'light',
    common: {
      black: '#000000',
      white: '#ffffff',
    },
    primary: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    secondary: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    error: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    warning: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    info: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    success: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    grey: {
      main: '',
      light: '',
      dark: '',
      contrastText: '',
    },
    contrastThreshold: 3,
    getContrastText: () => {},
    argumentColor: () => {},
    tonalOffset: 0.2,
    text: {
      primary: '',
      secondary: '',
      disabled: '',
    },
    background: {
      paper: '#fff',
      default: '#000',
    },
    action: {
      active: '',
      hover: '',
      hoverOpacity: '',
      selected: '',
      selectedOpacity: '',
      disabledBackground: '',
      focus: '',
      focusOpacity: '',
      activatedOpacity: '',
    },
  },
  spacing: (factor) => `${0.25 * factor}rem`,
  shape: {
    borderRadius: 4,
  },
  mixins: {},
  shadows,
  typography: {
    htmlFontSize: 16,
    pxToRem: () => {},
    fontFamily: '',
    fontSize: 14,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 400,
    fontWeightBold: 400,
    h1: {},
    h2: {},
    h3: {},
    h4: {},
    h5: {},
    h6: {},
    subtitle1: {},
    subtitle2: {},
    body1: {},
    body2: {},
    button: {},
    caption: {},
    overline: {},
  },
  transitions: {
    getHeightDuration: () => {},
    create: {},
    easing,
    duration: {
      shortest: 150,
      shorter: 200,
      short: 250,
      standard: 300,
      complex: 375,
      enteringScreen: 225,
      leavingScreen: 195,
    },
  },
  zIndex: {
    mobileStepper: 1000,
    fab: 1050,
    speedDial: 1050,
    appBar: 1100,
    drawer: 1200,
    modal: 1300,
    snackbar: 1400,
    tooltip: 1500,
  },
});

export default theme;
